# Generated by Django 3.1.3 on 2020-11-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
